name: Check for only allowed file changes

on:
  - push
  - pull_request

jobs:
  check:
    if: github.repository == 'orderlynetwork/documentation'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Node
        uses: actions/setup-node@v5
        with:
          node-version: "24"

      - name: Install PNPM
        run: npm install --global pnpm@9.0.6

      - name: Install dependencies
        run: npm ci

      - name: Test for no git diff
        run: |
          npm run update
          git diff --exit-code -- :^/sdks/tech-doc
